services:
  mysql:
    image: mysql:8.0
    container_name: loteria_project_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: loteria
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
      TZ: America/Sao_Paulo
    command:
      - --default-time-zone=America/Sao_Paulo
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
